USERS_SHEET_NAME = "Users"
CATEGORIES_SHEET_NAME = "Категории"
LIMITS_SHEET_NAME = "Лимиты_по_месяцам"
EXPENSES_SHEET_NAME = "Траты_по_месяцам"
SHOPPING_SHEET_NAME = "Список покупок Продукты"

MENU_VIEW_LIMITS_TEXT = "Посмотреть лимиты"
MENU_VIEW_EXPENSES_TEXT = "Посмотреть траты"
MENU_EXPENSES_TEXT = "Добавить трату"
MENU_SHOPPING_TEXT = "Список Покупок"
MENU_WEBAPP_TEXT = "Открыть Web App"
MENU_LIMITS_CALLBACK = "main:limits"
MENU_EXPENSES_CALLBACK = "main:expenses"
MENU_SHOPPING_CALLBACK = "main:shopping"

ACCESS_CACHE_TTL_SECONDS = 300
EXPENSE_SESSION_TTL_SECONDS = 900
SHOPPING_SESSION_TTL_SECONDS = 900

SHOPPING_ITEM_MAX_LEN = 120
